name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.1]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Bundle app
      run: yarn run build
    - name: Run tests
      run: yarn run test:all
    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.TOKEN }}
        external_repository: lwrooblewski/lwrooblewski.github.io
        publish_branch: master
        publish_dir: ./dist
